baseURL = 'https://main--vermillion-creponne-2c85a8.netlify.app/'
languageCode = 'en-us'
title = "Brandon Gutierrez's website"
theme = 'my-theme'

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    style = 'monokai'
    tabWidth = 4
    pygmentsUseClasses = true
    pygmentsCodeFences = true