baseURL = 'http://gutibran.com'
languageCode = 'en-us'
title = "Brandon Gutierrez's Website"
theme = 'mytheme'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
          
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = false
    noHl = false
    style = 'bw'
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 2

[params]
    buildDate = "not built yet"
    uniqueViews = 0
    siteBuilds = 0
    math = true